#!/bin/bash -e

change_interface() {

local INTERFACE=${1}; local ADDRESS=${2}; local NETMASK=${3}; local GATEWAY=${4}

#ip link show ${INTERFACE} | grep -qs "[<,]UP[,>]" && sudo ifdown --force ${INTERFACE}

sudo sed -i "/${INTERFACE}/d" /etc/network/interfaces
sudo cat > "/etc/network/interfaces.d/${INTERFACE}" << EOF
allow-hotplug ${INTERFACE}
auto ${INTERFACE}
iface ${INTERFACE} inet static
    address ${ADDRESS}
    netmask ${NETMASK}
EOF

[[ ! -z ${GATEWAY} ]] && sudo cat >> "/etc/network/interfaces.d/${INTERFACE}" << EOF
    gateway ${GATEWAY}
EOF

ip link show ${INTERFACE} | grep -qs "[<,]UP[,>]" && sudo ifdown --force ${INTERFACE}
sudo ifup ${INTERFACE}

}

change_hostname() {

local HOSTNAME=${1};

sudo cat 2> /dev/null > "/etc/hostname" << EOF
${HOSTNAME}
EOF

sudo hostname ${HOSTNAME} 2> /dev/null

sudo sed -i "/127.0.1.1/d" /etc/hosts 2> /dev/null
sudo cat 2> /dev/null >> "/etc/hosts" << EOF
127.0.1.1   ${HOSTNAME}
EOF

}